<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>08bac807-ba8d-4ed4-b41a-01e0bcf5274a</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Azure.Messaging.ServiceBus" Version="13.3.3" />
        <PackageReference Include="FastEndpoints" Version="8.1.0" />
        <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MessageContracts\MessageContracts.csproj" />
        <ProjectReference Include="..\AzureServiceBusAspire.ServiceDefaults\AzureServiceBusAspire.ServiceDefaults.csproj" />
        <ProjectReference Include="..\..\..\..\src\Flowly.AzureServiceBus\Flowly.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\..\..\src\Flowly.DeadLetters.SqlServer\Flowly.DeadLetters.SqlServer.csproj" />
        <ProjectReference Include="..\..\..\..\src\Flowly.Jobs.SqlServer\Flowly.Jobs.SqlServer.csproj" />
    </ItemGroup>

</Project>
