<Project>
  <PropertyGroup>
    <Authors>Rasmus Therkelsen</Authors>
    <Copyright>Copyright © Rasmus Therkelsen</Copyright>
    <PackageProjectUrl>https://github.com/rasmustherkelsen/flowly</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rasmustherkelsen/flowly</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>messaging;queue;background-service;azure-service-bus;rabbitmq;dotnet</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)docs/assets/flowly-icon.png" Pack="true" PackagePath="icon.png" />
  </ItemGroup>
</Project>
