// <auto-generated />
using System;
using Flowly.Jobs.DatabaseModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flowly.Jobs.SQLite.Migrations
{
    [DbContext(typeof(JobStateDataContext))]
    partial class JobStateDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.CustomJobState", b =>
                {
                    b.Property<Guid>("JobIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomState")
                        .HasColumnType("TEXT");

                    b.HasKey("JobIdentifier");

                    b.ToTable("CustomJobStates");
                });

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.Job", b =>
                {
                    b.Property<Guid>("JobIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FaultReason")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurringJob")
                        .HasColumnType("INTEGER");

                    b.Property<long>("JobTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Started")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobIdentifier");

                    b.HasIndex("JobTypeId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.JobAliveStatus", b =>
                {
                    b.Property<Guid>("JobIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAliveTimestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobIdentifier");

                    b.ToTable("JobAliveStatuses");
                });

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.JobType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.Job", b =>
                {
                    b.HasOne("Flowly.Jobs.DatabaseModel.JobType", "JobType")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("Flowly.Jobs.DatabaseModel.JobType", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
