<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <!--#if (UseRabbitMQ)-->
        <PackageReference Include="Flowly.RabbitMQ" Version="1.2.0" />
        <!--#else-->
        <PackageReference Include="Flowly.AzureServiceBus" Version="1.2.0" />
        <!--#endif-->
        <PackageReference Include="Flowly.OpenTelemetry" Version="1.2.0" />
        <!--#if (UseSqlServer)-->
        <PackageReference Include="Flowly.DeadLetters.SqlServer" Version="1.2.0" />
        <!--#endif-->
        <!--#if (UsePostgres)-->
        <PackageReference Include="Flowly.DeadLetters.Postgres" Version="1.2.0" />
        <!--#endif-->
        <!--#if (UseSQLite)-->
        <PackageReference Include="Flowly.DeadLetters.SQLite" Version="1.2.0" />
        <!--#endif-->
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MyAspireApp.Messages\MyAspireApp.Messages.csproj" />
        <ProjectReference Include="..\MyAspireApp.ServiceDefaults\MyAspireApp.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
