namespace Flowly;

/// <summary>
///     Interface representing the context of an event, including the event data and metadata such as message ID,
///     correlation ID, and enqueue time.
/// </summary>
/// <typeparam name="TEvent"></typeparam>
public interface IEventContext<out TEvent>
{
    /// <summary>
    ///     The event data associated with this context. This property provides access to the actual event object that is being
    ///     processed. The type of the event is specified by the generic type parameter TEvent, allowing for strong typing and
    ///     flexibility in handling different event types.
    /// </summary>
    TEvent Event { get; }

    /// <summary>
    ///     The unique identifier for the message associated with this event. This ID is typically generated by the underlying
    ///     message broker or transport.
    /// </summary>
    string MessageId { get; }

    /// <summary>
    ///     The correlation ID for the message associated with this event. This ID can be used to correlate related messages
    ///     and events within the system.
    /// </summary>
    string? CorrelationId { get; }

    /// <summary>
    ///     The time at which the message associated with this event was enqueued in the messaging system. This timestamp can
    ///     be used to track the age of the message and to implement time-based processing logic, such as handling messages
    ///     that have been in the queue for too long or implementing retry policies based on message age.
    /// </summary>
    DateTimeOffset EnqueuedAt { get; }
}