<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Flowly.Jobs</PackageId>
        <Description>Job state tracking and CRON scheduling for Flowly. Job state tracking requires an underlying database so take your dependency on Flowly.Jobs.X where X is the database you want to use.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Flowly\Flowly.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Flowly.Jobs.SqlServer" />
        <InternalsVisibleTo Include="Flowly.Jobs.Postgres" />
        <InternalsVisibleTo Include="Flowly.Jobs.SQLite" />
        <InternalsVisibleTo Include="Flowly.Jobs.Tests" />
        <InternalsVisibleTo Include="Flowly.Jobs.SqlServer.Tests" />
        <InternalsVisibleTo Include="Flowly.Jobs.Postgres.Tests" />
        <InternalsVisibleTo Include="Flowly.Jobs.SQLite.Tests" />
    </ItemGroup>

</Project>
