<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Flowly.AzureServiceBus.Aspire</PackageId>
        <Description>Aspire AppHost integration for Flowly Azure Service Bus.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Azure.ServiceBus" Version="13.4.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Flowly\Flowly.csproj" />
    </ItemGroup>

</Project>
